### PR TITLE
Add more framing types.

### PR DESCRIPTION
**Pull request by anuraaga**

### CODE REVIEW

**Comment by kenichi-fukushima** [comment]
What's our policy for backward-compatibility? We can make backward incompatible changes because we haven't cut a v1 release yet, can't we?

**Comment by kenichi-fukushima** [comment]
@gavinreaney Where can I find the statement? README.me of this project does not contain it.

**Comment by reiinakano** [comment]
@kenichi-fukushima https://github.com/infostellarinc/stellarstation-api/releases

**Comment by reiinakano** [comment]
It's in the releases tab of the repo

**Pull request merged**
